Add command test

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -10,6 +10,8 @@ chmod 600 .tmp/private_key
 
 echo "$PRIVATE_KEY" > .tmp/private_key
 
+echo "+++ Checking preconditions"
+
 echo "Testing SSH connection..."
 ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS} 'echo "Connection Test"' > /dev/null
 if [ $? -eq 0 ]; then
@@ -19,6 +21,9 @@ else
     exit 1
 fi
 
+commands=()
+allCommandsValid=true
+
 IFS=$'\n'
 for command in $BUILDKITE_COMMAND
 do
@@ -27,7 +32,7 @@ do
     echo "Processing command $rawCommand ..."
 
     echo "Checking if $rawCommand exists as script file on server."
-    ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS} "if [[ -f $rawCommand ]] ; then exit 0; else exit 1; fi"
+    ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS} "bash -s" -- < "if [[ -f $rawCommand ]] ; then exit 0; else exit 1; fi"
     if [ $? -eq 0 ]; then
         echo "Script file $rawCommand found on server."
         scriptFileOnServer=true
@@ -46,20 +51,61 @@ do
     fi
 
     echo "Checking if $rawCommand exists as command on server."
-    rawCommandSource=$(ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS} "command -v $rawCommand")
+    rawCommandSource=$(ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS} "bash -s" -- < "command -v $rawCommand")
     if [ $? -eq 0 ]; then
         echo "Command or script $rawCommand found on server: $rawCommandSource"
-        # echo "ssh user@server \"bash -s\" -- < $command"
+        $commandOnServer=true
     else
         echo "Command or script $rawCommand not found on server."
+        $commandOnServer=false
     fi
 
     echo "Checking if $rawCommand exists as command on agent."
     rawCommandSource=$(command -v $rawCommand)
     if [ $? -eq 0 ]; then
         echo "Command or script $rawCommand found on agent: $rawCommandSource"
-        # echo "ssh user@server \"bash -s\" -- < $command"
+        $commandOnAgent=true
     else
         echo "Command or script $rawCommand not found on agent."
+        $commandOnAgent=false
     fi
+
+    if [[ $scriptFileOnServer || $scriptFileOnAgent || $commandOnServer || $commandOnAgent ]]; then
+        echo "Command $command is valid and can be executed."
+    else
+        allCommandsValid=false
+    fi
+
+    if [[ $commandOnServer ]]; then
+        sshCommand="ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS}  \"bash -s\" -- < $command"
+        echo "Using command from server: $sshCommand"
+        commands+=(sshCommand)
+    elif [[ $scriptFileOnServer ]]; then
+        sshCommand="ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS}  \"bash $command\""
+        echo "Using script file from server: $sshCommand"
+        commands+=(sshCommand)
+    elif [[ $commandOnAgent ]]; then
+        sshCommand="ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS}  \"bash -s\" -- < $command"
+        echo "Using command from agent: $sshCommand"
+        commands+=(sshCommand)
+    elif [[ $scriptFileOnAgent ]]; then
+        sshCommand="ssh -i .tmp/private_key -p ${PORT} ${BUILDKITE_PLUGIN_SSH_USERNAME}@${BUILDKITE_PLUGIN_SSH_SERVER_ADDRESS}  \"bash -s\" -- < $command"
+        echo "Using script file from agent: $sshCommand"
+        commands+=(sshCommand)
+    fi
+done
+
+if [[ allCommandsValid ]]; then
+    echo "Preconditions are met."
+    echo "^^^ ---"
+else
+    echo "Preconditions are not met. Aborting execution."
+    exit 1
+fi
+
+echo "+++ Executing commands on remote server."
+for command in "${commands[@]}"
+do
+    "Executing command \"$command\""
+    eval $command
 done
